# Generated by Django 5.2.9 on 2026-01-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('core', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient'),
        ),
    ]
