# Generated by Django 5.2.9 on 2025-12-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_vendor_equipment_cost_equipment_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='barcode_data',
            field=models.CharField(blank=True, help_text='Scan barcode from product', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='barcode_data',
            field=models.CharField(blank=True, help_text='Scan barcode from product', max_length=100, null=True, unique=True),
        ),
    ]
