# Generated by Django 5.2.9 on 2025-12-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('google', 'Google Reviews'), ('twitter', 'Twitter'), ('other', 'Other')], max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='platforms/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5')),
                ('review_url', models.URLField(blank=True, null=True)),
                ('review_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reputation.platform')),
            ],
        ),
    ]
