# Generated by Django 5.2.9 on 2025-12-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
