# Generated by Django 5.2.9 on 2025-12-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_notes', models.TextField(blank=True, help_text='Observations by the doctor')),
                ('diagnosis', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True, help_text='Medicines and dosage')),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointmentrequest')),
            ],
        ),
    ]
