# Generated by Django 5.2.9 on 2025-12-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor_notes',
            field=models.TextField(help_text='Observations by the doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(help_text='Medicines and dosage'),
        ),
    ]
