# Generated by Django 5.2.9 on 2025-12-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_consultation_next_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='pharmacy_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
