# Generated by Django 5.2.9 on 2026-01-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_consultation_pharmacy_status'),
        ('core', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_comments',
            field=models.TextField(blank=True, help_text='Additional comments for the report'),
        ),
    ]
