# Generated by Django 5.2.9 on 2025-12-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('location', models.CharField(help_text='Department or Room Name', max_length=200)),
                ('status', models.CharField(choices=[('working', 'Working'), ('repair', 'Under Repair'), ('retired', 'Retired')], default='working', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipmentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_contact', models.CharField(help_text='Phone or Email', max_length=100)),
                ('terms', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_records', to='inventory.equipment')),
            ],
        ),
    ]
