# Generated by Django 5.2.9 on 2026-01-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_sale_patient_medicinereturn_medicinereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode/UPC', max_length=100, null=True, unique=True),
        ),
    ]
