# Generated by Django 5.2.9 on 2025-12-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('pharmacy', '0002_sale_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sale', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
    ]
