# Generated by Django 5.2.9 on 2025-12-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('inventory', '0003_consumable_barcode_data_equipment_barcode_data'),
        ('pharmacy', '0003_remove_sale_total_amount_sale_invoice_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='schedule_type',
            field=models.CharField(choices=[('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X'), ('OTC', 'Over the Counter')], default='OTC', help_text='Drug Schedule Classification', max_length=5),
        ),
        migrations.AddField(
            model_name='medicine',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Preferred Vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='admission',
            field=models.ForeignKey(blank=True, help_text='Linked IPD Admission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_requests', to='admissions.admission'),
        ),
        migrations.DeleteModel(
            name='PharmaVendor',
        ),
    ]
