# Generated by Django 5.2.9 on 2026-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_medicine_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Tax percentage', max_digits=5),
        ),
    ]
