# Generated by Django 5.2.9 on 2025-12-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='departments/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('qualifications', models.CharField(max_length=200)),
                ('specialization', models.CharField(help_text="Specific area of focus, e.g., 'Interventional Cardiology'", max_length=200)),
                ('bio', models.TextField()),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.department')),
            ],
        ),
    ]
