# Generated by Django 5.2.9 on 2025-12-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_consultation_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True, help_text='Medicines and dosage (legacy text field)'),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 1-0-1', max_length=50)),
                ('duration', models.CharField(help_text='e.g. 5 days', max_length=50)),
                ('instruction', models.CharField(blank=True, help_text='e.g. After food', max_length=200)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='appointments.consultation')),
            ],
        ),
    ]
