# Generated by Django 5.2.9 on 2026-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointmentrequest_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='token_id',
            field=models.CharField(blank=True, help_text='Daily Token ID e.g. 14Jan2026-01', max_length=50, null=True),
        ),
    ]
